# ループ周期 [Hz]
hz: 10

# デバッグ用
flag_slow_test: false # 可視化フラグ(パス・ノード)
flag_reverse: false   # way pointを逆にするか
sleep_time: 0.002     # 次のpublishまでの時間 [s]

# 経由点 [m]
way_points_x: [-4.5, 10.3, 11.9, 11.9, 11.1, -20.5, -21.5, -21.5, -20.5,  0.0]
way_points_y: [ 7.1,  7.1,  5.0,  1.0,  0.0,   0.0,   1.0,   5.0,   7.1,  7.1]
