# ループ周期 [Hz]
hz: 10

# デバッグ用
flag_slow_test: false # 可視化フラグ(パス・ノード)
sleep_time: 0.005     # 次のpublishまでの時間 [s]

# 経由点 [m]
way_points_x: [-6.0, 11.9, 11.9, -21.5, -21.5, -1.5]
way_points_y: [ 7.1,  7.1,  0.0,   0.0,   7.1,  7.1]

# 初期位置・姿勢
init_x: -6.0  # [m]
init_y:  7.1  # [m]
init_yaw: 0.0 # [rad]
