# ループ周期 [Hz]
hz: 10

# デバッグ用
is_visible: true  # 可視化フラグ(パス・ノード)
sleep_time: 0.005 # 次のpublishまでの時間 [s]

# 経由点 [m]
# way_points_x: [0.0, 11.1, 11.9, 11.9, 11.1, -19.2, -21.5, -21.5, -20.5, 0.0]
# way_points_y: [0.0,  0.0,  1.0, 13.5, 14.2,  14.2,  13.2,   1.2,   0.1, 0.0]
way_points_x: [-4.8, 10.3, 11.9, 11.9, 11.1, -20.5, -21.5, -21.5, -20.5, 0.0]
way_points_y: [ 7.1,  7.1,  5.0,  1.0,  0.0,   0.0,   1.0,   5.0,   7.1, 7.1]
