# --- クラスAMCL ---
hz: 10        # ループ周期 [Hz]
laser_step: 3 # 何本ずつレーザを見るか(全1080本)
particle_num: 200
init_x: 0.0
init_y: 0.0
init_yaw: 0.0
init_dev: 0.95
sensor_noise_ratio: 0.03
reset_threshold: 0.000001

# --- 柱に関する角度範囲の配列 [rad] ---
# 以下が無視される
# [0] < angle < [1], [2] < angle
# [num] -> num:index
ignore_angle_range_list: [rad(1.5*pi/16.0), rad(5.0*pi/16.0), rad(10.0*pi/16.0)]

# --- クラスOdomModel ---
ff: 0.19   # 直進1[m]で生じる道のりのばらつきの標準偏差
fr: 0.0001 # 回転1[rad]で生じる道のりのばらつきの標準偏差
rf: 0.13   # 直進1[m]で生じる向きのばらつきの標準偏差
rr: 0.2    # 回転1[rad]で生じる向きのばらつきの標準偏差
