way_points_x: [-9.0, 10.5, 11.9, 11.9, 11.0, -20.0, -21.5, -21.5, -20.0, 9.0]
way_points_y: [ 7.1,  7.1,  5.5, -0.2,  0.0,   0.0,   0.7,   5.8,   7.1, 7.1]
init_x: -9.0  # [m]
init_y:  7.1  # [m]
init_yaw: 0.0 # [rad]
