way_points_x: [0.0, -20.0, -21.5, -21.5, -21.0, -8.0, -5.5, -5.5,  -8.0, -19.0]
way_points_y: [7.1,   7.1,   5.8,  -0.3,   0.0,  0.0,  0.7,  5.8,   7.1,   7.1]
init_x: 0.0  # [m]
init_y: 7.1  # [m]
init_yaw: 3.14 # [rad]
